name: pragma_breeds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.11
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0
  riverpod: ^2.5.0
  url_launcher: ^6.2.5

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_native_splash:
  color: '#003C54'
  background_image: 'assets/images/logo.jpeg'

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.jpeg'
  min_sdk_android: 21
